### ISSUE TITLE
mac os

### ISSUE THREAD

**Issue by hiroki802** [t-cool/cl-exercise#1]
So far, cl-exercise doesn't work well on MacOS.
Could you write some codes for cl-exercise to run on MacOS High Sierra?

**Comment by fu7mu4** [comment]
It caused by sbcl.
Use clozure cl instead of sbcl on macOS High Sierra.

**Comment by fu7mu4** [comment]
on clozure cl 1.11, sometime Hunchentoot outputs that:
#<PROCESS hunchentoot-worker-127.0.0.1:53099(14) [Active] #x30200429E37D> requires access to Shared Terminal Input
;;; Type (:y 14) to yield control to this thread.

**Comment by tamamu** [comment]
This repository uses old install instruction.
I added fukamachi/proc-parse to dependencies, it may solve this issue.
(refer to https://github.com/tamamu/cl-exercise/commit/3d394b7e13a9462dfaaf9af8b61c76e4eca166c7)

```
$ ros install fukamachi/proc-parse
```

**Comment by hiroki802** [comment]
Thanks!!

**Comment by fu7mu4** [comment]
In clozure cl's ML, someone says that caused by thread, someone says hunchentoot cause this. ex. https://lists.clozure.com/pipermail/openmcl-devel/2009-September/006094.html
